name: "Notebooks"
version: "0.0.0.35"
slug: "notebooks"
description: "Keep Track of your notes"
panel_icon: mdi:notebook
startup: application
boot: "auto"
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 5000
ingress_entry: "/"
ingress_user: true
arch:
  - "armv7"
  - "armhf"
  - "aarch64"
  - "amd64"
  - "i386"
options: {}
schema: {}
map:
  - "config:rw"
