name: "Journaled"
version: "0.0.309"
slug: "journaled"
description: "UNSTABLE - Journaled is a multi user journaling app for Home Assistant."
startup: "application"
boot: "auto"
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 5000
ingress_stream: true
ingress_entry: "/"
ingress_user: true
arch:
  - "armv7"
  - "armhf"
  - "aarch64"
  - "amd64"
  - "i386"
options: {}
schema: {}
map:
  - "config:rw"