SAYINGS = [
    "What's happening today",
    "Care to share your thoughts",
    "Got anything on your mind",
    "What's the latest",
    "How are you feeling",
    "Any thoughts you'd like to jot down",
    "Let's capture this moment",
    "Time to reflect",
    "What's your story today",
    "What's inspiring you today",
    "Any reflections for today",
    "Let's put pen to paper",
    "Ready to journal",
    "What's worth noting today",
    "Let's hear it",
    "What's important to you right now",
    "What's crossing your mind",
    "Let's make sense of the day",
    "Anything you'd like to remember",
    "What's the mood today",
    "What's the highlight of your day",
    "What are you thinking about",
    "Share your thoughts",
    "Let's dive into your thoughts",
    "What's your take on today",
    "Got something to say",
    "What's going on",
    "How was your day",
    "Let's get writing",
    "What's your perspective",
    "Any insights today",
    "What's the vibe",
    "What's shaping your day",
    "Let's turn thoughts into words",
    "Your mind is full; care to unload",
    "What's brewing in your thoughts",
    "Open the floodgates of your mind",
    "Paint the page with your thoughts",
    "What's echoing in your mind",
    "Let's freeze this moment in words",
    "Got a thought worth capturing",
    "Let your pen speak",
    "What's stirring within",
    "Let your mind wander onto the page",
    "What's whispering in your mind",
    "Let's explore your inner landscape",
    "What's the narrative today",
    "What's beneath the surface",
    "Unveil your thoughts",
    "Let's trace your day in words",
    "What's resonating with you",
    "Leave a footprint of your thoughts",
    "What's the undercurrent of your day",
    "Cast your thoughts onto the page",
    "Let the page reflect your mind",
    "What's the pulse of your thoughts",
    "Let's give voice to your mind",
    "What's the lens through which you're seeing today",
    "Let's chronicle your journey",
    "What's in the tapestry of your mind",
    "Let's map your thoughts",
    "Unfold your day onto the page",
    "What's the horizon look like today",
    "What thoughts are orbiting your mind",
    "Sketch your day in words",
    "Any epiphanies worth noting",
    "What's the story only you can tell today",
    "Trace the footprints of your thoughts",
    "Unlock the day with your words",
    "Compose the melody of your mind",
    "Let your thoughts take the stage",
    "What's the dialogue in your mind",
    "Capture the essence of today",
    "What echoes linger from today",
    "What colors paint your mood today",
    "Unravel your thoughts onto the page",
    "What truths did you discover today",
    "Chart the course of your day",
    "Let your inner voice speak",
    "What questions are you pondering",
    "Pen down the whispers of your soul",
    "Reflect on your journey today",
    "What insights surfaced today",
    "Give words to your experiences",
    "What lessons did today bring",
    "Express what's ineffable",
    "Shed light on your inner world",
    "What dreams moved you today",
    "Let your thoughts find freedom here",
    "Transcribe your mind's wanderings",
    "What moments defined your day",
]

PAST_SAYINGS = [    
    "Your History",
    "Its hard to remember",
    "Process at your own pace",
    "Be kind to yourself",
    "The Past can be hard",
    "Your past",
    "Your memories",
    "Things that happened",
    "Your past thoughts",
    "Your past reflections",
    "Your past experiences",
    "Your past feelings",
]

INSPIRATIONAL_QUOTES = [
    "“You don’t have to control your thoughts. You just have to stop letting them control you.” – Dan Millman",
    "“It’s not the load that breaks you down, it’s the way you carry it.” – Lou Holtz",
    "“Sometimes the most productive thing you can do is relax.” – Mark Black",
    "“Almost everything will work again if you unplug it for a few minutes, including you.” – Anne Lamott",
    "“Self-care is giving the world the best of you, instead of what’s left of you.” – Katie Reed",
    "“Rest and self-care are so important. When you take time to replenish your spirit, it allows you to serve others from the overflow.” – Eleanor Brown",
    "“Take care of your body. It’s the only place you have to live.” – Jim Rohn",
    "“The greatest weapon against stress is our ability to choose one thought over another.” – William James",
    "“You can’t pour from an empty cup. Take care of yourself first.”",
    "“Work to live, don’t live to work.”",
    "“Mental health is not a destination, but a process. It's about how you drive, not where you’re going.” – Noam Shpancer",
    "“Sometimes the most important thing in a whole day is the rest we take between two deep breaths.” – Etty Hillesum",
    "“Your worth is not measured by your productivity.”",
    "“You are not a machine. You are a person. Treat yourself kindly.”",
    "“Never get so busy making a living that you forget to make a life.” – Dolly Parton",
    "“The key to keeping your balance is knowing when you’ve lost it.”",
    "“The time to relax is when you don’t have time for it.” – Sydney J. Harris",
    "“Taking care of yourself doesn’t mean me first, it means me too.” – L.R. Knost",
    "“Health is a state of body. Wellness is a state of being.” – J. Stanford",
    "“There is virtue in work and there is virtue in rest. Use both and overlook neither.” – Alan Cohen",
    "“Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.” – Oprah Winfrey",
    "“Taking care of yourself is part of taking care of others.” – Jennifer Williamson",
    "“Boundaries aren’t walls to keep people out, they’re the gates to let the right ones in.”",
    "“You are allowed to be both a masterpiece and a work in progress simultaneously.” – Sophia Bush",
    "“It’s okay to be a glowstick; sometimes we have to break before we shine.”",
    "“If you get tired, learn to rest, not to quit.” – Banksy",
    "“When you recover or discover something that nourishes your soul and brings joy, care enough about yourself to make room for it in your life.” – Jean Shinoda Bolen",
    "“Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain.” – Vivian Greene"
]


IMPORTANT_DATES = {
    "New Year's Day (Global)": "2024-01-01",
    "Chinese New Year": "2024-02-10",
    "Holi (India)": "2024-03-25",
    "International Women's Day (Global)": "2024-03-08",
    "Ramadan Begins (Islamic)": "2024-03-10",
    "Nowruz (Persian New Year)": "2024-03-20",
    "Easter (Christian)": "2024-03-31",
    "Earth Day (Global)": "2024-04-22",
    "Vesak (Buddhist)": "2024-05-23",
    "Mother's Day (Various)": "2024-05-12",
    "Pride Month (Global)": "2024-06-01",
    "Juneteenth (U.S.)": "2024-06-19",
    "Eid al-Fitr (Islamic)": "2024-04-09",
    "Father's Day (Various)": "2024-06-16",
    "Dragon Boat Festival (China)": "2024-06-10",
    "Independence Day (U.S.)": "2024-07-04",
    "Obon (Japan)": "2024-08-13",
    "Diwali (Hindu)": "2024-10-31",
    "Mid-Autumn Festival (China)": "2024-09-17",
    "Rosh Hashanah (Jewish)": "2024-10-02",
    "Yom Kippur (Jewish)": "2024-10-11",
    "Halloween (Various)": "2024-10-31",
    "Día de los Muertos (Mexico)": "2024-11-01",
    "Thanksgiving (U.S.)": "2024-11-28",
    "Hanukkah (Jewish)": "2024-12-25",
    "Christmas (Christian)": "2024-12-25",
    "Kwanzaa (African-American)": "2024-12-26",
    "World Mental Health Day (Global)": "2024-10-10",
    "International Day of Peace (Global)": "2024-09-21",
    "World Kindness Day (Global)": "2024-11-13",
    "Lunar New Year (East Asia)": "2024-02-10",
    "Songkran (Thailand)": "2024-04-13",
    "Tet (Vietnamese New Year)": "2024-02-10",
    "Self-Care Day (Global)": "2024-07-24"
}


from datetime import datetime
import random


def get_important_date(date=None):
    if date is None:
        date = datetime.now().strftime('%Y-%m-%d')
    for event, event_date in IMPORTANT_DATES.items():
        if event_date == date:
            return event
    return None

#functions to get random sayings/quotes
def get_random_saying():
    return random.choice(SAYINGS)

def get_random_inspirational_quote():
    return random.choice(INSPIRATIONAL_QUOTES)

def get_random_past_saying():
    return random.choice(PAST_SAYINGS)

