INSPIRATIONAL_QUOTES = [
    "“You don’t have to control your thoughts. You just have to stop letting them control you.” – Dan Millman",
    "“It’s not the load that breaks you down, it’s the way you carry it.” – Lou Holtz",
    "“Sometimes the most productive thing you can do is relax.” – Mark Black",
    "“Almost everything will work again if you unplug it for a few minutes, including you.” – Anne Lamott",
    "“Self-care is giving the world the best of you, instead of what’s left of you.” – Katie Reed",
    "“Rest and self-care are so important. When you take time to replenish your spirit, it allows you to serve others from the overflow.” – Eleanor Brown",
    "“Take care of your body. It’s the only place you have to live.” – Jim Rohn",
    "“The greatest weapon against stress is our ability to choose one thought over another.” – William James",
    "“You can’t pour from an empty cup. Take care of yourself first.”",
    "“Work to live, don’t live to work.”",
    "“Mental health is not a destination, but a process. It's about how you drive, not where you’re going.” – Noam Shpancer",
    "“Sometimes the most important thing in a whole day is the rest we take between two deep breaths.” – Etty Hillesum",
    "“Your worth is not measured by your productivity.”",
    "“You are not a machine. You are a person. Treat yourself kindly.”",
    "“Never get so busy making a living that you forget to make a life.” – Dolly Parton",
    "“The key to keeping your balance is knowing when you’ve lost it.”",
    "“The time to relax is when you don’t have time for it.” – Sydney J. Harris",
    "“Taking care of yourself doesn’t mean me first, it means me too.” – L.R. Knost",
    "“Health is a state of body. Wellness is a state of being.” – J. Stanford",
    "“There is virtue in work and there is virtue in rest. Use both and overlook neither.” – Alan Cohen",
    "“Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.” – Oprah Winfrey",
    "“Taking care of yourself is part of taking care of others.” – Jennifer Williamson",
    "“Boundaries aren’t walls to keep people out, they’re the gates to let the right ones in.”",
    "“You are allowed to be both a masterpiece and a work in progress simultaneously.” – Sophia Bush",
    "“It’s okay to be a glowstick; sometimes we have to break before we shine.”",
    "“If you get tired, learn to rest, not to quit.” – Banksy",
    "“When you recover or discover something that nourishes your soul and brings joy, care enough about yourself to make room for it in your life.” – Jean Shinoda Bolen",
    "“Life isn’t about waiting for the storm to pass; it’s about learning to dance in the rain.” – Vivian Greene"
]
