WRITING_PROMPTS = [
    "What was something small that made you smile today?",
    "Describe something that made you feel cozy.",
    "What’s one fun thing you did today?",
    "Did you learn something new today?",
    "What’s a favorite song or show from today?",
    "Who did you talk to today, and what did you chat about?",
    "Describe something you enjoyed doing this morning.",
    "What’s a small thing you’re grateful for?",
    "Did anything surprise you today?",
    "What’s a food or drink you enjoyed today?",
    "Where did you go today?",
    "What’s one thing that went well today?",
    "How did you relax or take a break?",
    "What’s something interesting you saw today?",
    "Did you spend time outside today?",
    "What’s something you’d like to do tomorrow?",
    "What was your favorite part of today?",
    "What made today different from yesterday?",
    "Describe something you noticed around you.",
    "How did you enjoy your free time today?",
    "What’s a little thing that brought you comfort today?",
    "Did you do something creative today?",
    "What’s one kind thing someone did for you?",
    "What did you do today that made you proud?",
    "How did you take care of yourself today?",
    "What’s something that made you laugh?",
    "Did you help someone today?",
    "What’s a smell or sound you enjoyed today?",
    "What’s a small goal you accomplished today?",
    "How did you show kindness today?",
    "What’s something you’re looking forward to?",
    "Did you discover a new interest today?",
    "What’s a comforting routine you enjoyed today?",
    "What did you do today that made you feel energized?",
    "What’s something beautiful you noticed today?",
    "Did you spend time with a pet or animal today?",
    "What’s a comforting thought you had today?",
    "How did you make today better for yourself or someone else?",
    "What’s something that challenged you today, and how did you handle it?",
    "What’s a piece of advice you heard today that you want to remember?",
    "Did you read something interesting today?",
    "What’s one thing that made you feel connected to others today?",
    "What’s a memory from today that you want to keep?",
    "Did you listen to any good music today?",
    "How did you express yourself today?",
    "What’s something you’re thankful for about your body today?",
    "Did you feel inspired today? What inspired you?",
    "What’s a positive change you made today?",
    "How did you unwind at the end of the day?",
    "What’s a place you spent time in today that felt special?",
    "Did you feel supported today? How so?",
    "What’s one thing you noticed today that you might usually overlook?",
    "What’s a little moment you want to remember from today?",
    "Did you laugh today? What made you laugh?",
    "What’s something nice you did for yourself today?",
    "How did you stay active today?",
    "What’s a hobby or activity you enjoyed today?",
    "Did you feel proud of anything today?",
    "What did you look forward to today?",
    "What’s something you’d like to do more often?",
    "How did you start your day?",
    "What’s a thought or idea you enjoyed thinking about today?",
    "Did you listen to any good music today?",
    "What’s something you felt excited about?",
    "How did you spend your evening?",
    "Did you get a chance to relax today?",
    "What’s something simple that you enjoyed?",
    "How did you connect with a friend or family member?",
    "Did you try something new today?",
    "What’s a goal you thought about today?",
    "Describe a way you felt calm today.",
    "What’s a favorite place you went to today?",
    "Did you enjoy something creative today?",
    "What’s a small accomplishment from today?",
    "Describe something you felt curious about.",
    "What’s something you appreciated about today’s weather?",
    "How did you spend a quiet moment today?",
    "What’s a favorite snack you had today?",
    "How did you unwind at the end of the day?",
    "What’s something you found interesting today?",
    "Did you take any photos today? What were they of?",
    "What’s a new idea you had today?",
    "What’s something small that made you feel content?",
    "How did you enjoy a routine today?",
    "Describe something that made you feel peaceful.",
    "Did you have a good conversation today?",
    "What’s something you looked forward to today?",
    "What’s a place you’d like to visit someday?",
    "How did you take care of yourself today?",
    "Describe something that felt satisfying.",
    "What’s something beautiful you noticed?",
    "Did you find something to laugh about today?",
    "What’s a cozy place you enjoyed today?",
    "Did you try anything different today?",
    "What’s a nice way you treated yourself?",
    "How did you wind down before bed?",
    "What’s something you want to improve about your day tomorrow?",
    "Did you experience any random acts of kindness today?",
    "What did you do today that made you feel accomplished?",
    "Did you spend time in nature today? How did it make you feel?",
    "What’s a book, article, or story you read today that left an impact?",
    "Did you share anything special with someone today?",
    "What’s something new you learned about yourself today?",
    "How did today make you feel hopeful for the future?",
    "What’s a favorite moment of stillness you experienced today?",
    "Did you find any beauty in unexpected places today?",
    "What’s a comforting activity you did before bed?",
    "What’s something that filled you with wonder today?",
    "How did you make time for yourself today?",
    "Did you feel inspired by someone or something today?",
    "What’s a new perspective you gained today?",
    "What’s one thing you’re excited to work on tomorrow?",
    "How did you embrace a challenge today?",
    "What made you feel supported and safe today?",
    "What’s a small victory you had today that made you smile?",
    "Did you notice any changes in yourself today, big or small?",
    "How did you practice patience today?",
    "What’s something funny that happened to you today?",
    "Did you do anything today that made you feel brave?",
    "How did you share joy with others today?",
    "What was something spontaneous you did today?",
    "What’s a moment you were fully present today?",
    "How did you express gratitude today?",
    "What’s something nostalgic that came to your mind today?",
    "Did you find a new way to solve a problem today?",
    "How did you make the most of today’s opportunities?"
]
